### ISSUE TITLE
any reference to "firewall { .. }" causes puppet to fail in a kickstart with Rocky8.5

### ISSUE THREAD

**Issue by sandynomad** [puppetlabs/puppetlabs-firewall#1033]
With 'firewall { .. }' in a manifest in a kickstart the puppet run always fails with:

    Error: Could not prefetch firewall provider 'iptables': Execution of '/sbin/iptables-save' returned 1: iptables-save/1.8.4 Failed to initialize nft: Protocol not supported
    Error: Failed to apply catalog: Execution of '/sbin/iptables-save' returned 1: iptables-save/1.8.4 Failed to initialize nft: Protocol not supported

The primary reason for this is that none of the nft modules are loaded with the install kernel:

    root@ci-00: / # uname -r
    4.18.0-348.el8.0.2.x86_64
    root@ci-00: / # lsmod | grep nft
    root@ci-00: / # 

Ideally puppet could throw an error and then continue running, or alternatively have a flag to ignore errors during the kickstart phase.

**Comment by sandynomad** [comment]
The issue still persists. It's been worked around by placing conditionals (either "if" or using "tags") near the use of the firewall module.

The thing that makes this difficult to solve is there is no "one true way" to know if puppet is running in a kickstart environment (or not).

**Comment by chelnak** [comment]
Thanks for the update!

I've removed the label from this PR and it will remain in our backlog of work!

**Comment by sandynomad** [comment]
"The issue still persists. It's been worked around by placing conditionals (either "if" or using "tags") near the use of the firewall module."
