### ISSUE TITLE
Firewall 7.0.0 doesnt handle integer port numbers.

### ISSUE THREAD

**Issue by robertc99** [puppetlabs/puppetlabs-firewall#1158]
I get the following error out of firewall 7.0.0

Error: undefined method `start_with?' for 22:Integer
Error: /Stage[network]/Nci::Firewall::Ruleset::Ssh::Staged/Nci::Firewall::Ruleset[ssh]/Firewall[100 allow ssh]/dport: change from '22' to 22 failed: undefined method `start_with?' for 22:Integer

I doesnt happen if you delete the iptables rule and rerun, it will create the firewall rule successfully.
But on a rerun of puppet when the rule exists, I get the error.

Its happy if I specify 
 
dport => "22"

but not with 

dport => 22

**Comment by david22swan** [comment]
Have found the source of the issue, the `dport` and `sport` sections on the `insync?` function need to be converted to a string for the comparison.

**Comment by david22swan** [comment]
Will have a fix up soon

**Comment by david22swan** [comment]
Fix up: https://github.com/puppetlabs/puppetlabs-firewall/pull/1160

**Comment by david22swan** [comment]
That's 7.0.2 released with the fix.

**Comment by robertc99** [comment]
that was quick. Thanks, seems to work fine
