### ISSUE TITLE
setting the dest to 'undef' after being set doesn't clear it

### ISSUE THREAD

**Issue by kbarber** [puppetlabs/puppetlabs-firewall#121]
We had a firewall rule defining a "destination", after some time we want to change the destination from the already set ip-range to everything (0.0.0.0/0). We did this by removing the destination entry.

This change didn't cause the firewall rules to be updated, as it now doesn't check the destination anymore.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
