### ISSUE TITLE
proto as an array of protocols

### ISSUE THREAD

**Issue by kbarber** [puppetlabs/puppetlabs-firewall#122]
<pre>
        firewall { '520 dns':
                chain => 'OUTPUT',
                dport => '53',
                proto => [ 'tcp','udp' ],
                action => 'accept',
        }
</pre>

Currently generates only tcp

<pre>
Chain OUTPUT (policy ACCEPT 133 packets, 14604 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           multiport dports 53 /* 520 dns */ 
</pre>

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
