### ISSUE TITLE
Persistence: flush shells out on every resource

### ISSUE THREAD

**Issue by dcarley** [puppetlabs/puppetlabs-firewall#135]
Improvements on #133

The `flush` method, and thus the shell out in `persist_iptables`, is called on every modified resource. It would be more cost effective to call it once after all Firewall/Firewallchain resources have been synced.

@kbarber, any idea if this is technically possible?

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
