### ISSUE TITLE
allow established or related sessions

### ISSUE THREAD

**Issue by linuxdan** [puppetlabs/puppetlabs-firewall#144]
From my iptables-save output:
-A INPUT -m state --state RELATED,ESTABLISHED -m comment --comment "000b allow established or related sessions" -j ACCEPT 

Then from "puppet resource firewall"

Error: Could not run: Parameter name failed on Firewall[RELATED,ESTABLISHED]: Invalid value "RELATED,ESTABLISHED". Valid values match /^\d+[[:alpha:][:digit:][:punct:][:space:]]+$/.

Tried reversing the order for my input, but iptables-save puts it in that order.

puppetlabs-firewall (v0.2.1)
puppet 3.1.1
RHEL 5, 64 bit

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
