### ISSUE TITLE
using log_prefix seems to result in error on second puppet run

### ISSUE THREAD

**Issue by dkindred** [puppetlabs/puppetlabs-firewall#148]
If we have the following

class rcac_firewall::post_accept_all {

```
firewall { '975 log test':
    state      => 'NEW',
    log_level  => 'debug',
    log_prefix => 'iptables A: ',
    jump       => 'LOG'
}
```

...
}

On the first puppet run the rule is inserted ok... however, on the second
run we get some errors like this:

---

info: Applying configuration version '1365457738'
err: /Firewall[975 log test]/log_level: change from iptables A:  to 7 failed: The iptables provider can not handle attribute log_level at /etc/puppet/modules/rcac_firewall/manifests/post_accept_all.pp:8
err: /Firewall[975 log test]/log_prefix: change from 7 to iptables A:  failed: The iptables provider can not handle attribute log_prefix at /etc/puppet/modules/rcac_firewall/manifests/post_accept_all.pp:8
notice: Finished catalog run in 18.76 seconds

---

If it is of interest, this is puppet version 2.7.21 running under RHEL 6.3.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
