### ISSUE TITLE
When address munging fails, there is no guidance as to where the failure actually occured

### ISSUE THREAD

**Issue by OllyButters** [puppetlabs/puppetlabs-firewall#157]
This is actually just this bug - http://projects.reductivelabs.com/issues/18104 I can't seem to see it here anywhere. I am having the same problem.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
