### ISSUE TITLE
Support Windows Firewall through win32ole/hnetcfg/fwpolicy2 API

### ISSUE THREAD

**Issue by ruckc** [puppetlabs/puppetlabs-firewall#158]
It would be nice to support other firewall engines such as Windows Firewall.  I have an almost working type/provider, but the terminology is quite different from iptables.  Windows uses remote/local instead of source/destination, there are also some other major differences.  I can generate a provider for puppetlabs-firewall, just not sure the best route.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
