### ISSUE TITLE
When state=> property is removed, from the resource definition, its not removed from the rule.

### ISSUE THREAD

**Issue by ruckc** [puppetlabs/puppetlabs-firewall#159]
Use case, when the below has been applied, and state is removed, its not removed from the rule, and type/provider doesn't detect any changes.

firewall{'0010 allow ssh':
  ensure=>present,
  action=>accept,
  proto=>tcp,
  dport=>22,
  state=>['NEW'],
}

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
