### ISSUE TITLE
unable to delete a PREROUTING chain rule

### ISSUE THREAD

**Issue by dkindred** [puppetlabs/puppetlabs-firewall#169]
If you have a rule like the following:

```
firewall { "090 preroute 192.168.1.1:80":
    chain       => 'PREROUTING',
    proto       => 'tcp',
    destination => "192.168.1.1",
    dport       => '80',
    toports     => '80',
    jump        => 'REDIRECT',
    table       => 'nat',
}
```

If you later delete the firewall rule, on the next puppet run it is unable to 
delete the rule with output something along the lines of:

err: /Firewall[090 preroute 192.168.1.1:80]/ensure: change from present to absent failed: Execution of '/sbin/iptables -D PREROUTING -d 192.168.1.1/32 -p tcp -m multiport --dports 80 -m comment --comment 090 preroute 192.168.1.1:80 -j REDIRECT --to-ports 80' returned 1: iptables: Bad rule (does a matching rule exist in that chain?).

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
