### ISSUE TITLE
Issue setting UID as username in OUTPUT chain

### ISSUE THREAD

**Issue by madAndroid** [puppetlabs/puppetlabs-firewall#170]
Hi guys, we're experiencing a problem whereby when we set a UID as a username, the run applies cleanly, but a subsequent run will attempt to amend the change by substituting the UID for the username.

For example:

``` ruby
class test_firewall {

        $uid = 'root'

        firewall { '00001 test uid':
            chain       => 'OUTPUT',
            proto       => 'tcp',
            dport       => '3189',
            source      => undef,
            destination => undef,
            action      => 'accept',
            uid         => $uid,
        }
}

class { 'test_firewall': }
```

results in (and repeated in subsequent runs):

``` ruby
vagrant@server:~$ sudo puppet apply --verbose --logdest console --detailed-exitcodes --show_diff --color=true firewall_test.pp
info: Applying configuration version '1366800808'
notice: /Firewall[00001 test uid]/uid: uid changed '0' to 'root'
notice: Firewall[00001 test uid](provider=iptables): Properties changed - updating rule
notice: Finished catalog run in 0.69 seconds
```

Is this expected behavior? If so, is there any way to set the UID as a username without experiencing the change on a subsequent run? 

Thanks,
Andrew

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
