### ISSUE TITLE
First run takes over 5 minutes on agent systems

### ISSUE THREAD

**Issue by ITBlogger** [puppetlabs/puppetlabs-firewall#185]
Hello,

We use PE 2.8 and when puppet first runs on a server/agent where iptables was previously unmanaged, the first run takes over 5 minutes.

After the run, the console reports various errors similar to:

Could not evaluate: getaddrinfo: Name or service not known Could not retrieve file metadata for puppet:///modules/pe_mcollective/plugins/agent/package.rb: getaddrinfo: Name or service not known at /opt/puppet/share/puppet/modules/pe_mcollective/manifests/server/plugins.pp:54

for the node.

Compared to normal behavior of Puppet, runs are taking a long time.

Thanks,

Alex

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
