### ISSUE TITLE
Cisco ASA Support - Features Question

### ISSUE THREAD

**Issue by alecdhuse** [puppetlabs/puppetlabs-firewall#198]
I'm interested in adding Cisco ASA support to this module.  I've been looking at the current syntax / features for iptables here and thinking about how I could adapt this for the ASAs.  

There are a few differences between iptables and ASA that might not be compatible and I wanted to get thoughts on this.  For example:  ASA doesn't have chains, the closest thing might be access-lists.  I'd like to get some opinions on if I should try to stick with a 'chain' feature or go with an 'acl' I've given an example what the acl might look like below:

 firewall { '000 accept all port 53 traffic from 8.8.8.8':
        acl             => 'access_in',
        action        => 'accept',
        proto          => udp,
        source       => '8.8.8.8',
        dport          => '53',
        destination => "any",
  }->

Also for Cisco firewalls the actions are permit and deny.  I think the action => 'accept' is pretty clear but someone with only a Cisco firewall background would put action => 'permit'  Would it be acceptable for the module to treat accept and permit as the same?

Thanks!

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
