### ISSUE TITLE
Unable to prefetch on el5 when no iptables rules loaded

### ISSUE THREAD

**Issue by mdsummers** [puppetlabs/puppetlabs-firewall#202]
CentOS 5.9, iptables-1.3.5-9.2.el5_8, puppet-2.6.16-1.el5

When no rules are loaded into iptables, it is not possible to manage firewall rules using this module. The following errors are returned in the puppet report:

Failed to generate additional resources using 'generate': Execution of '/sbin/iptables-save' returned 1
Could not prefetch firewall provider 'iptables': Execution of '/sbin/iptables-save' returned 1: 

On iptables-1.3.5, when no rules are loaded, iptables-save exits 1. This was changed in a later version of iptables. iptables-1.4.12, for example, exits 0 in the circumstances.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
