### ISSUE TITLE
Incorrect processing of built in chains

### ISSUE THREAD

**Issue by CtrlC-Root** [puppetlabs/puppetlabs-firewall#214]
So here's my puppet manifest http://tny.cz/63ae0209 which I apply like this in my node definitions:

``` puppet
node default
{
    stage {'config':
        before => Stage['main']
    }

    class {'linux::firewall':
        stage => 'config'
    }
}
```

About 10-20% of the time I get this error in my puppet agent's logs:

```
Execution of '/sbin/ip6tables -t filter -N INPUT' returned 1: ip6tables: Chain already exists.
```

Which doesn't make sense. Why is the firewall module attempting to create a built in chain? I'm running the latest version of puppet (3.2.2) and the firewall module (0.3.1). I've tried to correlate this problem to a pre-existing condition on the machine with no success. So I also don't know why this only happens some of the time, it would seem indicative of a missing relationship somewhere in my manifests, but I haven't been able to find one.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
