### ISSUE TITLE
Initial puppet run fails: firewall blocks all traffic

### ISSUE THREAD

**Issue by KlavsKlavsen** [puppetlabs/puppetlabs-firewall#239]
I currently fix this issue (on iniitial server setups), by doing a ctrl+z when puppet halts, and doing: iptables -F INPUT.

The iptables rules ONLY contain the reject rules - and is appearently loaded in - instead of waiting until the end, as a normal "service notify" would have.

This is on RHEL6.
# Firewall defaults - confine to Linux kernels

if ( $kernel == 'Linux' ) {
        class { 'firewall': }
        Firewall {
              before  => Class['cust_fw::post'],
              require => Class['cust_fw::pre'],
            }
        resources { "firewall":
                purge => true
        }
        class { ['cust_fw::pre', 'cust_fw::post']: }
}
# cust_fw

class cust_fw::pre {
  Firewall {
          require => undef,
  }

  firewall { '002 accept related established rules':
    proto   => 'all',
    state   => ['RELATED', 'ESTABLISHED'],
    action  => 'accept',
  }
  firewall { '001 accept all to lo interface':
    proto   => 'all',
    iniface => 'lo',
    action  => 'accept',
  }
  if ( $privatenetwork == 'yes' ) {
    # Default firewall rules
    firewall { '000 accept all icmp': proto   => 'icmp', action  => 'accept', }
    firewall { "000 allow snmp": proto => "udp", port => 161, action => "accept" }
    firewall { "004 allow nrpe": proto => "tcp", port => 5666, action => "accept", }
    firewall { "003 allow ssh": proto => "tcp", port => 22, action => "accept" }
  } else {
    firewall { "003 allow ssh": proto => "tcp", port => 22, action => "accept", source => 'x.x.x.0/24' }
    firewall { '000 accept some icmp': proto   => 'icmp', action  => 'accept', source => 'x.x.0.0/16' }
  }
}

class cust_fw::post {
  firewall { '998 log all':
    proto   => 'all',
    jump => LOG,
    log_level => 'debug',
    before  => undef,
  }
  firewall { '999 drop all':
    proto   => 'all',
    action  => 'drop',
    before  => undef,
  }
}

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
