### ISSUE TITLE
Always returns errors: "Invalid parameter src_range"

### ISSUE THREAD

**Issue by robrwo** [puppetlabs/puppetlabs-firewall#249]
Following the documentation at https://forge.puppetlabs.com/puppetlabs/firewall to use the Firewall module. it returns the error:

```
Error: Invalid parameter src_range(:src_range)
Error: /Firewall[000 accept all icmp]/ensure: change from absent to present failed: Invalid parameter src_range(:src_range)
```

No matter what values are specified for src_range, it still returns an error.

**Comment by petergmurphy** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
