### ISSUE TITLE
Unable to purge - Parameter name failed on Firewall["some_name"]

### ISSUE THREAD

**Issue by hmm01i** [puppetlabs/puppetlabs-firewall#256]
If a user manually adds a firewall rule with a comment that does not conform to the "name requirement" you get the below message and Puppet is unable to purge the rule.

```
Error: /Stage[main]/test::Base_fw/Resources[firewall]: Failed to generate additional resources using 'generate': Parameter name failed on Firewall[JPPF Server Port]: Invalid value "JPPF Server Port". Valid values match /^\d+[[:alpha:][:digit:][:punct:][:space:]]+$/.
```

In my case a user had entered the following rule

```
-A INPUT -p tcp -m multiport --ports 11111 -m comment --comment "JPPF Server Port" -j ACCEPT
```

The README says that Firewall type name is used for ordering of rules, but perhaps there should be another attribute where this is specified. Or maybe comments are only validated during rule creation so they don't interfere with purging.

If you add an additional attribute for this, it might make sense to concat the order with the comment/name for readability.

```
firewall { 'JPPF Server':
  order   => 010,
  proto   => 'tcp',
  action => 'accept',
  port    => 11111,
}
```

Resulting iptables comment:

```
"010 accept JPPF Server tcp port 11111"
```

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
