### ISSUE TITLE
firewall does NOT handle when iptables-save fails

### ISSUE THREAD

**Issue by KlavsKlavsen** [puppetlabs/puppetlabs-firewall#258]
on servers, where no one messed with the firewall setup - iptables-save command fails, and then the firewall module fails. This happens on CentOS/RHEL-5 atleast.

The fix is simple - one simply has to run:
iptables -L -n

and then iptables-save runs fine.

It's not a bug in firewall module - but since it's appearently not being fixed upstream - the firewall module could perhaps fix it, when it occurs?

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
