### ISSUE TITLE
toports should be only possible with MASQUERADE and REDIRECT jump targets.

### ISSUE THREAD

**Issue by traylenator** [puppetlabs/puppetlabs-firewall#263]
RHEL6

After adding some manifest 

``` puppet
firewall {'8443 routing':
       table => 'nat',
       proto => 'tcp',
       jump => 'redirect',
       dport => 443,
       chain => 'prerouting',
      toports => 8443,
}
```

this fails with

``` bash
/sbin/iptables -I prerouting 1 -t nat -p tcp -m multiport --dports 443 -m comment --comment 8443 routing -j redirect --to-ports 8443
iptables v1.4.7: unknown option `--to-ports'
```

From the man page --to-ports is only ever valid if the jump target is _REDIRECT_ or _MASQUERADE_.

Would be good to verify in the puppet layer that _toports_ is only ever set if jump target is strictly _REDIRECT_ or _MASQUERADE_.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
