### ISSUE TITLE
Add support generic iptables parameters (ie. for TCPMSS clamp-mss-to-pmtu)

### ISSUE THREAD

**Issue by apeeters** [puppetlabs/puppetlabs-firewall#272]
Although the jump parameter accepts any valid chain name, some require additional parameters. For example TCPMSS accepts two parameters set-mss and clamp-mss-to-pmtu.

Please add suport for generic iptables parameters, or TCPMSS (and any other) chains.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
