### ISSUE TITLE
Working with groups

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppetlabs-firewall#283]
I miss a feature that allows to assign rolles to one of two kinds of groups.

Group one: e.g. webserver defines wich roles the server has.
Group two defines to which roles the server is allowed to connect.

these groups are exported to the master and make complex firewalling very easy.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
