### ISSUE TITLE
nftables provider

### ISSUE THREAD

**Issue by daenney** [puppetlabs/puppetlabs-firewall#284]
Linux kernel 3.13 brought back nftables which is also considered the way forward. Though iptables won't be removed anytime soon an nftables provider for the firewall type should be built.

nftables also has a slew of functionality that iptables doesn't like atomic updates to one or more rules through single netlink transactions which though not critical for this module would be a very nice thing to have for people with large rulesets.

As an added bonus we would now have one provider that can handle IPv4, IPv6, Ethernet and ARP.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
