### ISSUE TITLE
nf_conntrack_ftp is not loaded

### ISSUE THREAD

**Issue by KlavsKlavsen** [puppetlabs/puppetlabs-firewall#317]
According to an old issue ( http://projects.puppetlabs.com/issues/15505 ) - which should have been moved to github, but which I cannot find - rhel 5/6 should itself figure out which contrack modules are needed.

If that's the case ( I haven't found any docu on this), then it doesn't work :(

IMHO the firewall module should allow for conntrack to be enabled.

Currently I have to manually specify (using a module_autoload module I wrote) that nf_conntrack_ftp should be loaded at boot, for ftp to actually work :(

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
