### ISSUE TITLE
firewall rules not working on ubuntu: No chain/target/match by that name.

### ISSUE THREAD

**Issue by slider1337** [puppetlabs/puppetlabs-firewall#318]
Hi,

I get the following error for alle rules that I try to apply to my puppet node:

Error: Execution of '/sbin/iptables -I INPUT 1 -t filter -p icmp -m comment --comment 000 accept all icmp -j ACCEPT' returned 1: iptables: No chain/target/match by that name.

The problem is the "-m comment --comment 000 accept all icmp" part. If I remove this part from the command it is working. Is there a possibility to remove comments?

Best regards,
Benedikt

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
